POST http://localhost:8080/instagram/accidentallywesanderson

###

POST http://localhost:8080/twitter/chelseafc

###

GET http://localhost:8080/instagram/accidentallywesanderson
Accept: application/rss+xml

###

GET http://localhost:8080/twitter/chelseafc
Accept: application/rss+xml

###
